In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Flatten,Dense

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Split the image folder in training and testing folder

In [2]:
pip install split-folders

In [ ]:
import splitfolders

In [ ]:
splitfolders.ratio(input='/content/drive/MyDrive/PetImages',output='/content/drive/MyDrive/cat_dog_images',ratio=(0.8,0.2))

Copying files: 25002 files [14:50, 28.08 files/s]


Applying the Data Augmentation

In [3]:
data_aug = ImageDataGenerator(rotation_range=10,width_shift_range=0.2,height_shift_range=0.25,brightness_range=(0.2, 0.8),
                              shear_range=0.2,zoom_range=0.2,horizontal_flip=True,vertical_flip=True,
                              rescale=1./255)

In [4]:
train_data = data_aug.flow_from_directory(directory='/content/drive/MyDrive/cat_dog_images/train',target_size=(100,100),
                             class_mode='binary')

Found 19998 images belonging to 2 classes.


In [5]:
train_data

No of batches

In [6]:
len(train_data)

625

Accessing the first batch

In [7]:
next(train_data)

(array([[[[0.02745098, 0.02745098, 0.01960784],
          [0.02745098, 0.02745098, 0.01960784],
          [0.03137255, 0.02745098, 0.02352941],
          ...,
          [0.04705883, 0.04705883, 0.04705883],
          [0.05490196, 0.05490196, 0.04705883],
          [0.05490196, 0.05490196, 0.05490196]],
 
         [[0.02745098, 0.02745098, 0.01960784],
          [0.02745098, 0.02745098, 0.01960784],
          [0.03137255, 0.02745098, 0.02352941],
          ...,
          [0.04705883, 0.04705883, 0.04705883],
          [0.0509804 , 0.0509804 , 0.04705883],
          [0.05490196, 0.05490196, 0.0509804 ]],
 
         [[0.02745098, 0.02745098, 0.01960784],
          [0.02745098, 0.02745098, 0.01960784],
          [0.03137255, 0.02745098, 0.02352941],
          ...,
          [0.04705883, 0.04705883, 0.04313726],
          [0.0509804 , 0.0509804 , 0.04705883],
          [0.05490196, 0.05490196, 0.0509804 ]],
 
         ...,
 
         [[0.03921569, 0.03529412, 0.03137255],
          [0.03529

In [8]:
len(next(train_data))

2

Accessing all the images of batch 1

In [9]:
next(train_data)[0]

array([[[[0.5254902 , 0.49803925, 0.3372549 ],
         [0.5254902 , 0.49803925, 0.3372549 ],
         [0.5254902 , 0.49803925, 0.3372549 ],
         ...,
         [0.2901961 , 0.28627452, 0.29803923],
         [0.28627452, 0.2784314 , 0.29411766],
         [0.28627452, 0.28235295, 0.29803923]],

        [[0.5058824 , 0.48235297, 0.32156864],
         [0.5058824 , 0.48235297, 0.32156864],
         [0.5019608 , 0.4784314 , 0.31764707],
         ...,
         [0.30980393, 0.30588236, 0.32156864],
         [0.2901961 , 0.28627452, 0.29803923],
         [0.27450982, 0.26666668, 0.28235295]],

        [[0.5058824 , 0.48235297, 0.32156864],
         [0.5058824 , 0.48235297, 0.32156864],
         [0.5058824 , 0.48235297, 0.32156864],
         ...,
         [0.28627452, 0.28627452, 0.29803923],
         [0.27450982, 0.27450982, 0.28627452],
         [0.27058825, 0.26666668, 0.28235295]],

        ...,

        [[0.14117648, 0.09803922, 0.03529412],
         [0.14117648, 0.09803922, 0.03529412]

All the labels of images in batch 1

In [10]:
next(train_data)[1]

array([0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0.],
      dtype=float32)

In [11]:
next(train_data)[0][0]

array([[[0.21176472, 0.20392159, 0.20000002],
        [0.21176472, 0.20392159, 0.20000002],
        [0.21176472, 0.20392159, 0.20000002],
        ...,
        [0.11764707, 0.07843138, 0.04705883],
        [0.11764707, 0.07843138, 0.04705883],
        [0.11764707, 0.07843138, 0.04313726]],

       [[0.21176472, 0.20392159, 0.20000002],
        [0.21176472, 0.20392159, 0.20000002],
        [0.21176472, 0.20392159, 0.20000002],
        ...,
        [0.11764707, 0.07450981, 0.04705883],
        [0.11764707, 0.07450981, 0.04705883],
        [0.1137255 , 0.07450981, 0.04313726]],

       [[0.21176472, 0.20392159, 0.20000002],
        [0.21176472, 0.20392159, 0.20000002],
        [0.21176472, 0.20392159, 0.20000002],
        ...,
        [0.12156864, 0.07450981, 0.04705883],
        [0.12156864, 0.07843138, 0.04705883],
        [0.11764707, 0.07843138, 0.04705883]],

       ...,

       [[0.13725491, 0.06666667, 0.02352941],
        [0.13333334, 0.0627451 , 0.01960784],
        [0.13725491, 0

In [12]:
next(train_data)[1][0]

0.0

In [13]:
train_data.class_indices

{'Cat': 0, 'Dog': 1}

In [14]:
model = Sequential()

In [15]:
model.add(Conv2D(40,kernel_size=(3,3),activation='relu'))
model.add(MaxPool2D(strides=1))

model.add(Conv2D(50,kernel_size=(3,3),activation='relu'))
model.add(MaxPool2D(strides=1))

model.add(Conv2D(60,kernel_size=(3,3),activation='relu'))
model.add(MaxPool2D(strides=1))

model.add(Flatten())

model.add(Dense(100,activation='relu'))
model.add(Dense(50,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [16]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics='accuracy')

In [ ]:
model.fit(train_data,epochs=50)